/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 if the process is alive. Never checks dependencies — see /ready for that.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 if this instance can currently serve traffic.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build and version metadata
         * @description Returns the running application's name, version, and environment.
         */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a product image
         * @description Accepts product metadata and a single image file, validates and stores the file, then either queues it for background processing (202 Accepted, the default) or processes it synchronously in this same request (201 Created) depending on ASYNC_PIPELINE__ENABLED.
         */
        post: operations["upload_product_api_v1_products_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/check-duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check whether a product would be a duplicate
         * @description Accepts product metadata and a single image file and reports whether it looks like a duplicate of an existing product. Never stores or indexes anything (Phase 8) — for that, use POST /products/upload with DUPLICATE_DETECTION__MODE=warn or block.
         */
        post: operations["check_duplicate_api_v1_products_check_duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a product's background-processing status
         * @description Returns the status/progress/current stage of the background job processing this product (Phase 12). The counterpart to GET /jobs/{job_id}, looked up by product_id instead of job_id.
         */
        get: operations["get_product_status_api_v1_products__product_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recommendations for an already-uploaded product
         * @description Returns ranked recommendations for a product identified by ID, using its already-indexed embeddings and catalog metadata (or a worker-precomputed cache entry, Phase 12). 'similar' anchors on the full image+text profile; 'related' anchors on text/category alone.
         */
        get: operations["get_recommendations_api_v1_products__product_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an indexed product's catalog metadata
         * @description Resolves a product ID to the metadata stored alongside its vectors — name, brand, category, price, extracted attributes, tags and quality score. Recommendations, duplicate decisions and explanations all return bare product IDs; this is how a client turns one back into a product.
         */
        get: operations["get_product_api_v1_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve several product IDs at once
         * @description Resolves up to 100 product IDs in one round trip, for views that render many products at once (a recommendation list, a set of duplicate candidates). Unknown IDs are returned in `missing` rather than failing the request, so a partially-stale list still renders what exists.
         */
        post: operations["get_products_batch_api_v1_products_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a product's stored image
         * @description Returns the standardized (processed) image for a product. Pass `thumbnail=true` for a small variant suitable for cards and result lists. Returns 404 when the product carries no stored image — distinct from the product not existing.
         */
        get: operations["get_product_image_api_v1_products__product_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search for similar products by image, text, or both
         * @description Accepts an optional query image and/or an optional text query — at least one is required — plus optional brand/category/price-range filters, and returns the most similar previously uploaded products, ranked by similarity score. Providing both an image and text runs a weighted hybrid search across both.
         */
        post: operations["search_products_api_v1_products_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the evaluation benchmark
         * @description Runs the configured evaluation dataset (or a subset of it, via query_ids/limit) against hybrid search, duplicate detection, and the recommendation engine, returning aggregate and per-query metrics.
         */
        post: operations["run_evaluation_api_v1_evaluation_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/compare-reranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare evaluation metrics with reranking disabled vs. enabled
         * @description Runs the configured evaluation dataset (or a subset of it, via query_ids/limit) twice — once with cross-encoder reranking forced off, once forced on — and returns both reports plus the metric deltas between them.
         */
        post: operations["compare_reranking_api_v1_evaluation_compare_reranking_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/dead-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every job that exhausted its retries
         * @description Returns the current status of every job in the dead-letter queue — jobs that failed enough times to stop being retried automatically.
         */
        get: operations["get_dead_letter_jobs_api_v1_jobs_dead_letter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a background job's current status
         * @description Returns a queued/running/completed/failed background job's current status, progress, and current stage.
         */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every registered model
         * @description Returns every registered model version across every model type.
         */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every registered model of one type
         * @description Returns every registered model version for the given model type.
         */
        get: operations["list_models_by_type_api_v1_models__type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{type}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the active model for one type
         * @description Returns the currently active model for the given model type.
         */
        get: operations["get_active_model_api_v1_models__type__active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{product_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain a product's recommendations
         * @description Returns one explanation trace per recommended product — why each was recommended.
         */
        get: operations["recommendation_trace_api_v1_recommendations__product_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duplicates/{product_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain a product's duplicate decision
         * @description Returns the explanation trace for whether the product looks like a duplicate.
         */
        get: operations["duplicate_trace_api_v1_duplicates__product_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/explanations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain every AI decision about a product
         * @description Combines the product's duplicate-decision trace and its recommendation traces into one explanation tree.
         */
        get: operations["product_explanations_api_v1_products__product_id__explanations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Estimate a fair price for a described product
         * @description Estimates a fair market price for a product described by name/brand/category/description, from semantically similar priced products.
         */
        post: operations["estimate_price_api_v1_pricing_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate a fair price for an indexed product
         * @description Estimates a fair market price for an already-indexed product, by ID.
         */
        get: operations["price_indexed_product_api_v1_pricing__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operational analytics dashboard
         * @description Today's usage, the trailing-window usage, and how many models are active.
         */
        get: operations["dashboard_api_v1_analytics_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model inventory analytics
         * @description Per model type: the active version, lifecycle status, and registered-version count, plus the trailing window's usage.
         */
        get: operations["model_analytics_api_v1_analytics_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline throughput and latency
         * @description The trailing window's upload/duplicate/recommendation/search throughput and average product-processing latency, as a labeled report.
         */
        get: operations["pipeline_api_v1_analytics_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trend report for one metric
         * @description Returns a daily/weekly/monthly trend for one event metric, as JSON (default) or a Markdown table (format=markdown).
         */
        get: operations["trends_api_v1_analytics_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organizations
         * @description Lists every organization (requires the manage-organization permission).
         */
        get: operations["list_organizations_api_v1_organizations_get"];
        put?: never;
        /**
         * Bootstrap a new organization
         * @description Creates an organization, its default tenant, and an initial OWNER API key (returned once). The one open enterprise endpoint — every other requires a key.
         */
        post: operations["create_organization_api_v1_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the tenant's API keys
         * @description Lists the caller's tenant's API keys (metadata only, never the raw secret).
         */
        get: operations["list_api_keys_api_v1_api_keys_get"];
        put?: never;
        /**
         * Create an API key
         * @description Creates an API key for the caller's tenant. The new key's role cannot exceed the caller's own permissions (no privilege escalation). The raw key is returned once.
         */
        post: operations["create_api_key_api_v1_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{prefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API key
         * @description Revokes one of the caller's tenant's API keys by its prefix.
         */
        delete: operations["revoke_api_key_api_v1_api_keys__prefix__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the tenant's audit log
         * @description Returns the caller's tenant's most recent audit events, newest first.
         */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the tenant's request usage
         * @description Returns the caller's tenant's requests-today count and its configured quotas.
         */
        get: operations["get_usage_api_v1_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operational health dashboard
         * @description Reports Redis/Qdrant reachability, queue depth, active-model count, configured worker concurrency, and process uptime.
         */
        get: operations["system_health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate platform statistics
         * @description Reports uptime, worker concurrency, queue depth, in-flight and dead-lettered job counts, and active/registered model counts.
         */
        get: operations["system_stats_api_v1_system_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyticsEvent
         * @description A countable operational event, tallied per day by the analytics layer.
         * @enum {string}
         */
        AnalyticsEvent: "upload" | "duplicate_check" | "recommendation" | "search";
        /**
         * AnalyticsReportResponse
         * @description Response body for `GET /analytics/pipeline` (a labeled window report).
         */
        AnalyticsReportResponse: {
            /** Period */
            period: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            usage: components["schemas"]["UsageMetricsInfo"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * ApiKeyCreateRequest
         * @description Request body for `POST /api-keys`.
         */
        ApiKeyCreateRequest: {
            /** Name */
            name: string;
            /** @default member */
            role: components["schemas"]["Role"];
        };
        /**
         * ApiKeyCreationResponse
         * @description Response for the create endpoints — the raw `key` is shown here exactly once.
         */
        ApiKeyCreationResponse: {
            api_key: components["schemas"]["ApiKeyInfo"];
            /** Key */
            key: string;
        };
        /**
         * ApiKeyInfo
         * @description API-safe view of an `ApiKey` — metadata only, never the raw secret.
         */
        ApiKeyInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Prefix */
            prefix: string;
            /** Revoked */
            revoked: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AuditEventInfo
         * @description API-safe view of an `AuditEvent`.
         */
        AuditEventInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Resource */
            resource?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_check_duplicate_api_v1_products_check_duplicate_post */
        Body_check_duplicate_api_v1_products_check_duplicate_post: {
            /**
             * Name
             * @description Product name.
             */
            name: string;
            /**
             * File
             * @description The product image file.
             */
            file: string;
            /** Brand */
            brand?: string | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Price
             * @description Product price, used by cross-encoder verification's price rule.
             */
            price?: number | null;
            /**
             * Top K
             * @description Overrides DUPLICATE_DETECTION__TOP_K for this call.
             */
            top_k?: number | null;
            /**
             * Threshold
             * @description Overrides DUPLICATE_DETECTION__THRESHOLD for this call.
             */
            threshold?: number | null;
        };
        /** Body_search_products_api_v1_products_search_post */
        Body_search_products_api_v1_products_search_post: {
            /**
             * File
             * @description Optional query image.
             */
            file?: string | null;
            /**
             * Query
             * @description Optional text query.
             */
            query?: string | null;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /** Brand */
            brand?: string | null;
            /** Category */
            category?: string | null;
            /** Min Price */
            min_price?: number | null;
            /** Max Price */
            max_price?: number | null;
        };
        /** Body_upload_product_api_v1_products_upload_post */
        Body_upload_product_api_v1_products_upload_post: {
            /**
             * Name
             * @description Product name.
             */
            name: string;
            /**
             * File
             * @description The product image file.
             */
            file: string;
            /** Brand */
            brand?: string | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Price */
            price?: number | null;
        };
        /**
         * ComparableProductInfo
         * @description API-safe view of one `ComparableProduct`.
         */
        ComparableProductInfo: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Price */
            price: number;
            /** Similarity */
            similarity: number;
            /** Name */
            name?: string | null;
            /** Brand */
            brand?: string | null;
            /** Category */
            category?: string | null;
        };
        /**
         * ConfidenceBreakdownInfo
         * @description API-safe view of a `ConfidenceBreakdown`.
         */
        ConfidenceBreakdownInfo: {
            /** Components */
            components?: components["schemas"]["DecisionWeightInfo"][];
            /** Total */
            total: number;
        };
        /**
         * DashboardResponse
         * @description Response body for `GET /analytics/dashboard`.
         */
        DashboardResponse: {
            today: components["schemas"]["UsageMetricsInfo"];
            window: components["schemas"]["UsageMetricsInfo"];
            /** Window Days */
            window_days: number;
            /** Active Models */
            active_models: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * DecisionReasonInfo
         * @description API-safe view of one `DecisionReason`.
         */
        DecisionReasonInfo: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Weight */
            weight?: number | null;
        };
        /**
         * DecisionWeightInfo
         * @description API-safe view of one `DecisionWeight` contribution.
         */
        DecisionWeightInfo: {
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** Weight */
            weight: number;
            /** Contribution */
            contribution: number;
        };
        /**
         * DuplicateCandidateInfo
         * @description API-safe view of one ranked `app.models.duplicate_candidate.DuplicateCandidate`.
         */
        DuplicateCandidateInfo: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Image Similarity */
            image_similarity: number;
            /** Text Similarity */
            text_similarity: number;
            /** Metadata Similarity */
            metadata_similarity: number;
            /** Attribute Similarity */
            attribute_similarity: number;
            /** Overall Similarity */
            overall_similarity: number;
        };
        /**
         * DuplicateCheckResponse
         * @description Response body for `POST /api/v1/products/check-duplicate`.
         *
         *     `signals`/`matched_product` are `None` when no candidate was found at
         *     all (an empty catalog, or a genuinely novel product) — there is no
         *     "winning" candidate to report on.
         *
         *     `cross_encoder_score`/`retrieval_similarity`/`reasons` (Phase 15) are
         *     populated only when `DUPLICATE_VERIFICATION__ENABLED` is on: the
         *     cross-encoder relevance of the matched product, its raw embedding
         *     retrieval similarity, and the human-readable factors behind the
         *     verdict. When verification is off they stay `None`/empty — every
         *     pre-Phase-15 field keeps its exact meaning, so the response is
         *     backward compatible.
         */
        DuplicateCheckResponse: {
            /** Duplicate */
            duplicate: boolean;
            /** Confidence */
            confidence: number;
            /** Reason */
            reason: string;
            /** Matched Product */
            matched_product?: string | null;
            signals?: components["schemas"]["DuplicateSignalBreakdown"] | null;
            /** Top Candidates */
            top_candidates?: components["schemas"]["DuplicateCandidateInfo"][];
            /** Cross Encoder Score */
            cross_encoder_score?: number | null;
            /** Retrieval Similarity */
            retrieval_similarity?: number | null;
            /** Reasons */
            reasons?: string[];
        };
        /**
         * DuplicateInfo
         * @description API-safe summary of a `DuplicateDecision` (Phase 8).
         *
         *     Deliberately a summary, not the full internal decision: `top_candidates`
         *     (every candidate's per-signal breakdown) is useful detail for the
         *     dedicated `POST /products/check-duplicate` endpoint (Milestone 5),
         *     where checking for duplicates *is* the request's whole purpose, but
         *     would be excess detail on every single upload response. `is_duplicate`
         *     is `False` with `matched_product=None` both when detection genuinely
         *     found no match and when it didn't run at all
         *     (`DuplicateDetectionMode.OFF`) — see `Product.duplicate_decision`'s
         *     own docstring for why that field is never itself optional.
         */
        DuplicateInfo: {
            /** Is Duplicate */
            is_duplicate: boolean;
            /** Confidence */
            confidence: number;
            /** Reason */
            reason: string;
            /** Matched Product */
            matched_product?: string | null;
        };
        /**
         * DuplicateSignalBreakdown
         * @description The winning candidate's four independent similarity signals.
         *
         *     Derived from `DuplicateDecision.top_candidates[0]` (the same data
         *     `DuplicateCandidateInfo` above exposes per-candidate) — not a second,
         *     independent computation — so a caller doesn't have to reconstruct
         *     "which candidate won" from the `top_candidates` list themselves.
         */
        DuplicateSignalBreakdown: {
            /** Image */
            image: number;
            /** Text */
            text: number;
            /** Metadata */
            metadata: number;
            /** Attribute */
            attribute: number;
        };
        /**
         * EmbeddingInfo
         * @description API-safe view of a generated image embedding.
         *
         *     Deliberately excludes `app.models.embedding.ImageEmbedding`'s `vector`
         *     field — a raw 512-float (or whatever `dimension` is) array has no use
         *     to an API consumer today (no similarity search or persistence exists
         *     yet) and would just bloat the response, so only the model identity and
         *     shape are exposed, mirroring `ProcessedImageInfo` excluding server
         *     filesystem paths for the same "don't leak internal data that has no
         *     external use" reasoning.
         */
        EmbeddingInfo: {
            /** Model Name */
            model_name: string;
            /** Dimension */
            dimension: number;
        };
        /**
         * EvaluationMetricsInfo
         * @description API-safe view of `app.models.retrieval_metrics.RetrievalMetrics`.
         */
        EvaluationMetricsInfo: {
            /** Precision At K */
            precision_at_k?: {
                [key: string]: number;
            };
            /** Recall At K */
            recall_at_k?: {
                [key: string]: number;
            };
            /** Ndcg At K */
            ndcg_at_k?: {
                [key: string]: number;
            };
            /** Hit Rate At K */
            hit_rate_at_k?: {
                [key: string]: number;
            };
            /**
             * Mrr
             * @default 0
             */
            mrr: number;
            /**
             * Average Latency Seconds
             * @default 0
             */
            average_latency_seconds: number;
            /**
             * Query Count
             * @default 0
             */
            query_count: number;
        };
        /**
         * EvaluationQueryResultInfo
         * @description API-safe view of `app.models.evaluation_result.EvaluationQueryResult`.
         */
        EvaluationQueryResultInfo: {
            /** Query Id */
            query_id: string;
            /** Task Type */
            task_type: string;
            /** Retrieved Products */
            retrieved_products?: string[];
            /**
             * Latency Seconds
             * @default 0
             */
            latency_seconds: number;
            /** Precision At K */
            precision_at_k?: {
                [key: string]: number;
            };
            /** Recall At K */
            recall_at_k?: {
                [key: string]: number;
            };
            /** Ndcg At K */
            ndcg_at_k?: {
                [key: string]: number;
            };
            /** Hit Rate At K */
            hit_rate_at_k?: {
                [key: string]: number;
            };
            /**
             * Reciprocal Rank
             * @default 0
             */
            reciprocal_rank: number;
            /** Error */
            error?: string | null;
        };
        /**
         * EvaluationRunRequest
         * @description Optionally restricts one evaluation run to a subset of the configured dataset.
         *
         *     Every field defaults to `None` ("run everything") — a caller can
         *     `POST` with an empty body (or omit it entirely) to run the full
         *     dataset, matching `scripts/benchmark.py`'s own default behavior.
         *     `query_ids` and `limit` can be combined: `query_ids` filters first,
         *     `limit` then caps however many of those matches actually run.
         */
        EvaluationRunRequest: {
            /**
             * Query Ids
             * @description If given, only run these query IDs.
             */
            query_ids?: string[] | null;
            /**
             * Limit
             * @description If given, only run the first N (post-filter) queries.
             */
            limit?: number | null;
        };
        /**
         * EvaluationRunResponse
         * @description Response body for `POST /api/v1/evaluation/run`.
         *
         *     `summary` is a short, human-readable one-liner (matching
         *     `scripts/benchmark.py`'s own console output) for a caller that just
         *     wants a quick read without parsing the full metrics structure.
         *     `average_latency_seconds` is computed across *every* successfully-
         *     evaluated query regardless of task type — a single top-level number
         *     alongside `overall_metrics`' own per-task-type breakdown, per the
         *     phase spec's own "Latency" bullet distinct from "Overall Metrics."
         *     `models` (Phase 13) records which model was active, per type, when
         *     this run happened — a client can compare `models`/`overall_metrics`
         *     across two runs to see which model version produced which score.
         */
        EvaluationRunResponse: {
            /** Summary */
            summary: string;
            /** Dataset Size */
            dataset_size: number;
            /** Total Duration Seconds */
            total_duration_seconds: number;
            /** Average Latency Seconds */
            average_latency_seconds: number;
            /** Failure Count */
            failure_count: number;
            /** Overall Metrics */
            overall_metrics?: {
                [key: string]: components["schemas"]["EvaluationMetricsInfo"];
            };
            /** Query Results */
            query_results?: components["schemas"]["EvaluationQueryResultInfo"][];
            /** Models */
            models?: components["schemas"]["ModelInfoResponse"][];
        };
        /**
         * ExplanationResponse
         * @description Response body for the decision-trace endpoints.
         *
         *     `breakdown`/`confidence` are `None` when the decision had no composite
         *     score to break down (e.g. a purely qualitative explanation). `reasons`
         *     is the structured evidence; `summary` is the human-readable one-liner
         *     a caller can surface directly.
         */
        ExplanationResponse: {
            /** Decision Type */
            decision_type: string;
            /** Subject Id */
            subject_id?: string | null;
            /** Summary */
            summary: string;
            /** Confidence */
            confidence?: number | null;
            /** Reasons */
            reasons?: components["schemas"]["DecisionReasonInfo"][];
            breakdown?: components["schemas"]["ConfidenceBreakdownInfo"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ExportFormat
         * @description Response format for the analytics trend export (Phase 18).
         * @enum {string}
         */
        ExportFormat: "json" | "markdown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness probe response: "is the process alive at all?"
         *
         *     Deliberately minimal — a liveness probe should never do real work (no
         *     dependency checks); it just proves the ASGI server is accepting
         *     requests and running application code. See `ReadinessResponse` for the
         *     "can this instance actually serve traffic?" question.
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * JobStatusResponse
         * @description Response body for `GET /jobs/{job_id}` and `GET /products/{id}/status`.
         *
         *     The two routes return the exact same shape — a client that started
         *     with a `job_id` (from `UploadAcceptedResponse`) or a `product_id`
         *     (already known from its own upload request) can poll whichever it
         *     has on hand.
         */
        JobStatusResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Current Stage */
            current_stage: string;
            /** Retry Count */
            retry_count: number;
            /** Max Retries */
            max_retries: number;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ModelAnalyticsResponse
         * @description Response body for `GET /analytics/models`.
         */
        ModelAnalyticsResponse: {
            /** Models */
            models?: components["schemas"]["ModelUsageInfo"][];
            window: components["schemas"]["UsageMetricsInfo"];
            /** Window Days */
            window_days: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * ModelInfoResponse
         * @description API-safe view of `ModelInfo` — metadata only, no runtime inference.
         */
        ModelInfoResponse: {
            /** Model Name */
            model_name: string;
            /** Version */
            version: string;
            /** Model Type */
            model_type: string;
            /** Status */
            status: string;
            /** Dimension */
            dimension: number;
            /** Description */
            description: string;
            /** Provider */
            provider: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ModelType
         * @description Which model-loading service a registered model belongs to.
         * @enum {string}
         */
        ModelType: "image_embedding" | "text_embedding" | "reranker";
        /**
         * ModelUsageInfo
         * @description API-safe view of one `ModelUsage`.
         */
        ModelUsageInfo: {
            /** Model Type */
            model_type: string;
            /** Active Model */
            active_model?: string | null;
            /** Active Version */
            active_version?: string | null;
            /** Status */
            status?: string | null;
            /** Registered Versions */
            registered_versions: number;
        };
        /**
         * OrganizationBootstrapResponse
         * @description Response for `POST /organizations`: the org, its default tenant, and an owner key.
         */
        OrganizationBootstrapResponse: {
            organization: components["schemas"]["OrganizationInfo"];
            tenant: components["schemas"]["TenantInfo"];
            api_key: components["schemas"]["ApiKeyCreationResponse"];
        };
        /**
         * OrganizationCreateRequest
         * @description Request body for `POST /organizations` (bootstrap).
         */
        OrganizationCreateRequest: {
            /** Name */
            name: string;
        };
        /**
         * OrganizationInfo
         * @description API-safe view of an `Organization`.
         */
        OrganizationInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PricingRequest
         * @description Request body for `POST /pricing/estimate` — price a described (not-yet-indexed) product.
         *
         *     Retrieval uses the product's text (name/brand/category/description),
         *     so at least a `name` is required; `top_k`/`strategy` are per-request
         *     overrides of the configured defaults.
         */
        PricingRequest: {
            /** Name */
            name: string;
            /** Brand */
            brand?: string | null;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Top K
             * @description Overrides PRICING__TOP_K.
             */
            top_k?: number | null;
        };
        /**
         * PricingResponse
         * @description Response body for the pricing endpoints.
         *
         *     `status` discriminates the two states. When it is `"no_estimate"`,
         *     `estimated_price` is `null` -- never `0.0` -- and `confidence` carries no
         *     meaning, because there is no estimate to be confident about. Clients must
         *     branch on `status` rather than testing the price for a sentinel.
         */
        PricingResponse: {
            /** Status */
            status: string;
            /** Estimated Price */
            estimated_price: number | null;
            /** Confidence */
            confidence: string;
            /** Confidence Score */
            confidence_score: number;
            /** Strategy */
            strategy: string;
            /** Comparable Count */
            comparable_count: number;
            /** Pricing Reason */
            pricing_reason: string;
            /** Comparables */
            comparables?: components["schemas"]["ComparableProductInfo"][];
        };
        /**
         * ProcessedImageInfo
         * @description API-safe view of a processed image's dimensions and format.
         *
         *     Deliberately excludes `app.models.image_metadata.ImageMetadata`'s
         *     `original_path`/`processed_path` fields — those are real server
         *     filesystem paths, which (per Phase 2A's rationale for `ProductImage`
         *     only ever exposing a generated `stored_filename`, never a path) must
         *     never appear in an API response.
         */
        ProcessedImageInfo: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Format */
            format: string;
            /** Color Mode */
            color_mode: string;
        };
        /**
         * ProductBatchRequest
         * @description A request to resolve several product IDs at once.
         */
        ProductBatchRequest: {
            /**
             * Product Ids
             * @description Product IDs to resolve. At most 100.
             */
            product_ids: string[];
        };
        /**
         * ProductBatchResponse
         * @description The products that resolved, and the IDs that did not.
         *
         *     Unknown IDs are reported rather than silently omitted, and the endpoint
         *     does not 404 for them: a partially-stale recommendation list is a normal
         *     state, and a client resolving ten cards should still render the nine that
         *     exist. `missing` lets it show a real "product not found" state for the
         *     tenth instead of an ambiguous placeholder.
         */
        ProductBatchResponse: {
            /** Products */
            products?: components["schemas"]["ProductSummary"][];
            /** Missing */
            missing?: string[];
            /**
             * Resolved At
             * Format: date-time
             */
            resolved_at: string;
        };
        /**
         * ProductCreate
         * @description Product metadata submitted alongside an image upload.
         *
         *     Constructed by `app/api/products.py` from individual `Form(...)`
         *     parameters (not bound directly via `Annotated[ProductCreate, Form()]`
         *     — see that module's docstring for why combining a Form-model
         *     parameter with a `File()` upload doesn't spread fields the way it
         *     does in isolation), and again by `ProductService` to hold the
         *     normalized field values. Not parsed from a JSON body — a file upload
         *     and JSON can't share one request body, so the request is entirely
         *     `multipart/form-data`.
         */
        ProductCreate: {
            /**
             * Name
             * @description Product name.
             */
            name: string;
            /** Brand */
            brand?: string | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Price */
            price?: number | null;
        };
        /**
         * ProductExplanationsResponse
         * @description Aggregate explanation tree for one product (`GET /products/{id}/explanations`).
         *
         *     Combines the product's duplicate-decision trace (`duplicate`, `None`
         *     when nothing to report) and its recommendation traces
         *     (`recommendations`) into one view — the full "why the platform decided
         *     what it did about this product."
         */
        ProductExplanationsResponse: {
            /** Product Id */
            product_id: string;
            duplicate?: components["schemas"]["ExplanationResponse"] | null;
            /** Recommendations */
            recommendations?: components["schemas"]["ExplanationResponse"][];
        };
        /**
         * ProductImage
         * @description Metadata describing one image file `UploadService` has stored.
         *
         *     `stored_filename` is a generated identifier, never the client-supplied
         *     `original_filename` — see `UploadService` for why (path-traversal /
         *     collision avoidance).
         */
        ProductImage: {
            /** Original Filename */
            original_filename: string;
            /** Stored Filename */
            stored_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /**
         * ProductSearchResponse
         * @description Response body for `POST /api/v1/products/search`.
         */
        ProductSearchResponse: {
            /** Results */
            results: components["schemas"]["ProductSearchResult"][];
        };
        /**
         * ProductSearchResult
         * @description One similar product found for a search query.
         *
         *     Deliberately excludes the query's or the match's raw embedding vector
         *     — nothing outside this codebase has a use for a raw float array today,
         *     and returning one would leak internal representation for no benefit
         *     (the same "don't expose data a client can't act on yet" reasoning
         *     `EmbeddingInfo`, Phase 4, already established for the upload response).
         *     `matched_modalities` (Phase 6) tells a caller whether a result matched
         *     on image, text, or both, without revealing anything about *how*.
         */
        ProductSearchResult: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Score */
            score: number;
            /** Matched Modalities */
            matched_modalities: string[];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * ProductSummary
         * @description An indexed product's catalog metadata, as stored alongside its vectors.
         *
         *     Deliberately a *summary*: it carries what a client needs to render and
         *     reason about a product, not the internals. Filesystem paths and raw
         *     embeddings are never exposed here -- the same rule
         *     `ProcessedImageInfo` already documents for image paths.
         */
        ProductSummary: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Name */
            name?: string | null;
            /** Brand */
            brand?: string | null;
            /** Category */
            category?: string | null;
            /** Price */
            price?: number | null;
            /** Description */
            description?: string | null;
            /** Color */
            color?: string | null;
            /** Material */
            material?: string | null;
            /** Gender */
            gender?: string | null;
            /** Season */
            season?: string | null;
            /** Style */
            style?: string | null;
            /** Tags */
            tags?: string[];
            /** Quality Score */
            quality_score?: number | null;
        };
        /**
         * ReadinessResponse
         * @description Readiness probe response: "can this instance currently serve traffic?"
         *
         *     `checks` is an empty dict for now — there are no dependencies (database,
         *     vector store, cache) to check yet. The shape is deliberately a mapping
         *     of check-name to boolean so later milestones can add entries
         *     (`{"database": True, "vector_store": False}`) without changing the
         *     response's shape or breaking existing clients.
         */
        ReadinessResponse: {
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
            /** Checks */
            checks?: {
                [key: string]: boolean;
            };
        };
        /**
         * RecommendationInfo
         * @description One ranked recommendation.
         *
         *     `product_id` is the only product-identifying field — there's no
         *     persistence layer yet (see `backend/README.md`) to resolve a full
         *     product record from, the same limitation `UploadResponse`/
         *     `ProductSearchResult` already live with.
         */
        RecommendationInfo: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Score */
            score: number;
            reason: components["schemas"]["RecommendationReasonInfo"];
            /** Explanation */
            explanation: string;
        };
        /**
         * RecommendationReasonInfo
         * @description API-safe view of `app.models.recommendation_reason.RecommendationReason`.
         */
        RecommendationReasonInfo: {
            /** Matched Attributes */
            matched_attributes?: string[];
            /** Matched Tags */
            matched_tags?: string[];
            /**
             * Shared Brand
             * @default false
             */
            shared_brand: boolean;
            /**
             * Shared Category
             * @default false
             */
            shared_category: boolean;
        };
        /**
         * RecommendationType
         * @description Which recommendation strategy `RecommendationEngineService` should use.
         *
         *     Only `SIMILAR` and `RELATED` are implemented this phase — `SIMILAR`
         *     anchors on the target product's full hybrid (image + text) profile,
         *     `RELATED` anchors on text/category alone (decoupled from pure visual
         *     likeness). `COMPLEMENTARY` ("goes well with," e.g. recommending socks
         *     for a pair of shoes) is intentionally reserved, unimplemented — it
         *     needs a *different* kind of relationship (products that pair well
         *     together, not products that resemble each other) that neither
         *     similarity signal here can express; the phase spec explicitly leaves
         *     it "future-ready" rather than asking for a placeholder algorithm.
         * @enum {string}
         */
        RecommendationType: "similar" | "related" | "complementary";
        /**
         * RecommendationsResponse
         * @description Response body for `GET /api/v1/products/{product_id}/recommendations`.
         */
        RecommendationsResponse: {
            /** Recommendation Type */
            recommendation_type: string;
            /** Recommendations */
            recommendations?: components["schemas"]["RecommendationInfo"][];
        };
        /**
         * RerankComparisonResponse
         * @description Response body for `POST /api/v1/evaluation/compare-reranking` (Phase 11).
         *
         *     `without_reranking`/`with_reranking` are each shaped exactly like
         *     `EvaluationRunResponse` (the same dataset, evaluated once with
         *     reranking forced off and once forced on) so a caller can reuse
         *     whatever it already does with a normal run's response; `improvement`
         *     is the `after - before` delta per task type/metric, the phase spec's
         *     own worked example ("MRR: Before 0.81, After 0.90") made explicit
         *     rather than requiring the caller to diff the two reports itself.
         */
        RerankComparisonResponse: {
            without_reranking: components["schemas"]["EvaluationRunResponse"];
            with_reranking: components["schemas"]["EvaluationRunResponse"];
            /** Improvement */
            improvement?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /**
         * Role
         * @description The role attached to an API key, granting a fixed set of permissions.
         * @enum {string}
         */
        Role: "owner" | "admin" | "member" | "viewer";
        /**
         * SystemHealthResponse
         * @description Response body for `GET /system/health`.
         *
         *     `redis`/`qdrant` are `"healthy"`/`"unhealthy"` strings (not booleans)
         *     to match the phase spec's own example payload. `workers` is the
         *     configured worker concurrency, not a live process count — see
         *     `SystemHealthService`'s docstring.
         */
        SystemHealthResponse: {
            /** Redis */
            redis: string;
            /** Qdrant */
            qdrant: string;
            /** Workers */
            workers: number;
            /** Queue Depth */
            queue_depth: number;
            /** Active Models */
            active_models: number;
            /** Uptime */
            uptime: string;
        };
        /**
         * SystemStatsResponse
         * @description Response body for `GET /system/stats` — aggregate platform statistics.
         */
        SystemStatsResponse: {
            /** Uptime */
            uptime: string;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Worker Concurrency */
            worker_concurrency: number;
            /** Queue Depth */
            queue_depth: number;
            /** Jobs In Flight */
            jobs_in_flight: number;
            /** Dead Letter Size */
            dead_letter_size: number;
            /** Active Models */
            active_models: number;
            /** Registered Models */
            registered_models: number;
        };
        /**
         * TenantInfo
         * @description API-safe view of a `Tenant`.
         */
        TenantInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TraceBundleResponse
         * @description A subject's ordered list of explanation traces (its "decision timeline").
         *
         *     Used by `GET /recommendations/{id}/trace` — one `traces` entry per
         *     recommended product, newest decision first as produced by the engine.
         */
        TraceBundleResponse: {
            /** Subject Id */
            subject_id: string;
            /** Count */
            count: number;
            /** Traces */
            traces?: components["schemas"]["ExplanationResponse"][];
        };
        /**
         * TrendGranularity
         * @description The period length one point in an analytics trend report spans (Phase 18).
         *
         *     Fixed-length windows (not calendar months) keep the buckets
         *     deterministic and trivially derivable from the per-day counters:
         *     `DAILY` is one day, `WEEKLY` seven, `MONTHLY` thirty.
         * @enum {string}
         */
        TrendGranularity: "daily" | "weekly" | "monthly";
        /**
         * UploadAcceptedResponse
         * @description Response body for `POST /api/v1/products/upload` when the async pipeline is enabled (Phase 12).
         *
         *     Returned with `202 Accepted` instead of `UploadResponse`'s `201
         *     Created` — processing hasn't happened yet, only been queued.
         *     `status` is always `"pending"` at this point (the job was just
         *     created); `status_url` is the exact `GET /products/{id}/status` path
         *     a client can poll (also reachable via `GET /jobs/{job_id}` using
         *     `job_id` instead), so a caller doesn't have to construct either URL
         *     itself.
         */
        UploadAcceptedResponse: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Status */
            status: string;
            /** Status Url */
            status_url: string;
        };
        /**
         * UploadResponse
         * @description Response body for `POST /api/v1/products/upload`.
         *
         *     No database row exists yet (Phase 2B processes but does not persist —
         *     see `backend/README.md`). `product_id`, `checksum_sha256`,
         *     `processed_image`, `embedding`, and `duplicate` all come from
         *     `app.models.product.Product`, the internal domain object
         *     `ProductService` builds; `product` reflects the *normalized* fields
         *     (trimmed, cased, sluggified, price-rounded), not the raw submitted
         *     values, since that's what was actually processed and would (in a
         *     later phase) be persisted.
         */
        UploadResponse: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            product: components["schemas"]["ProductCreate"];
            image: components["schemas"]["ProductImage"];
            /** Checksum Sha256 */
            checksum_sha256: string;
            processed_image: components["schemas"]["ProcessedImageInfo"];
            embedding: components["schemas"]["EmbeddingInfo"];
            duplicate: components["schemas"]["DuplicateInfo"];
        };
        /**
         * UsageMetricsInfo
         * @description API-safe view of `UsageMetrics`.
         */
        UsageMetricsInfo: {
            /** Uploads */
            uploads: number;
            /** Duplicate Checks */
            duplicate_checks: number;
            /** Recommendations */
            recommendations: number;
            /** Searches */
            searches: number;
            /** Average Processing Seconds */
            average_processing_seconds: number;
        };
        /**
         * UsageResponse
         * @description Response body for `GET /usage`.
         */
        UsageResponse: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Requests Today */
            requests_today: number;
            /** Daily Request Quota */
            daily_request_quota: number;
            /** Rate Limit Per Minute */
            rate_limit_per_minute: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VersionResponse
         * @description Build/version metadata: what's actually deployed, and where.
         */
        VersionResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    upload_product_api_v1_products_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_product_api_v1_products_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"] | components["schemas"]["UploadAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_duplicate_api_v1_products_check_duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_check_duplicate_api_v1_products_check_duplicate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_status_api_v1_products__product_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_api_v1_products__product_id__recommendations_get: {
        parameters: {
            query?: {
                top_k?: number | null;
                recommendation_type?: components["schemas"]["RecommendationType"];
            };
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_products_batch_api_v1_products_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_image_api_v1_products__product_id__image_get: {
        parameters: {
            query?: {
                /** @description Return a small variant instead of the full image. */
                thumbnail?: boolean;
            };
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The product's stored image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description The product has no stored image. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_products_api_v1_products_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_search_products_api_v1_products_search_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_evaluation_api_v1_evaluation_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EvaluationRunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_reranking_api_v1_evaluation_compare_reranking_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EvaluationRunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerankComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dead_letter_jobs_api_v1_jobs_dead_letter_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"][];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfoResponse"][];
                };
            };
        };
    };
    list_models_by_type_api_v1_models__type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: components["schemas"]["ModelType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_model_api_v1_models__type__active_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: components["schemas"]["ModelType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendation_trace_api_v1_recommendations__product_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceBundleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_trace_api_v1_duplicates__product_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_explanations_api_v1_products__product_id__explanations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductExplanationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_price_api_v1_pricing_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PricingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    price_indexed_product_api_v1_pricing__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_analytics_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    model_analytics_api_v1_analytics_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelAnalyticsResponse"];
                };
            };
        };
    };
    pipeline_api_v1_analytics_pipeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsReportResponse"];
                };
            };
        };
    };
    trends_api_v1_analytics_trends_get: {
        parameters: {
            query?: {
                /** @description Which event to trend. */
                metric?: components["schemas"]["AnalyticsEvent"];
                granularity?: components["schemas"]["TrendGranularity"];
                /** @description How many periods to include. */
                periods?: number;
                format?: components["schemas"]["ExportFormat"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organizations_api_v1_organizations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationInfo"][];
                };
            };
        };
    };
    create_organization_api_v1_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationBootstrapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_v1_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyInfo"][];
                };
            };
        };
    };
    create_api_key_api_v1_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_v1_api_keys__prefix__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_api_v1_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
        };
    };
    system_health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemHealthResponse"];
                };
            };
        };
    };
    system_stats_api_v1_system_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatsResponse"];
                };
            };
        };
    };
}
