#!/usr/bin/env python3
"""Seed a coherent demo catalog through the real upload API.

    python scripts/seed_catalog.py
    python scripts/seed_catalog.py --base-url https://api.example.com

Why this exists, separately from the smoke dataset
--------------------------------------------------

`scripts/smoke/dataset.py` seeds eight products spanning footwear, kitchenware,
bags and lighting, priced 24.50-134.99. That set is deliberately scattered:
each item is a *fixture* proving a specific behaviour, and the smoke suite
asserts relationships against it. It is not touched here.

But it makes a poor demonstration. A catalog of eight items across four
unrelated categories, priced 24-135, produces output that says more about the
seed data than about the system:

* pricing has one or two same-category comparables at most, so every estimate
  reports LOW confidence honestly but unimpressively;
* mixed price scales make any estimate look wrong at a glance -- a real upload
  priced 4000 against a catalog topping out at 135 cannot produce a sensible
  number;
* recommendations have nothing to rank, because there is barely a category to
  rank within.

This script seeds a catalog that resembles a real one instead: **one coherent
domain, one price scale, enough depth per segment that the intelligence
features have something to work with.**

What it seeds
-------------

Twenty-four running and training shoes across six brands and four segments,
priced on a single consistent scale (2,499-14,999). Enough that:

* every product has 5+ same-category comparables, so pricing has real evidence
  and confidence reflects agreement rather than scarcity;
* segments (road / trail / court / lifestyle) give recommendations a
  meaningful ranking problem;
* colours are spread across the palette, which is worth having now that colour
  is read from the product rather than the backdrop;
* one deliberate near-twin pair still exercises duplicate detection.

Everything is generated: the images are drawn by `scripts/smoke/images.py`, so
they are deterministic, dependency-free, and carry no licensing question.
Every product is named "Demo ..." and described as synthetic, exactly as the
smoke dataset is -- this is demonstration data and must never read as real.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "smoke"))

import images
from client import SmokeClient, SmokeError

#: One scale for the whole catalog. Mixed scales are the single biggest reason
#: a price estimate "looks wrong" regardless of correctness.
CURRENCY_NOTE = "Prices are on one consistent scale (approx. INR), 2,499-14,999."

#: The category holding the bulk of the catalog.
#:
#: "men-shoes" rather than "footwear" because that is what a user actually
#: types when uploading a running shoe -- an observed run used exactly this
#: string and every comparable was excluded, because the catalog held none.
#: Pricing matches categories exactly (casefolded), so the demo catalog has to
#: use the same vocabulary a demo upload will.
CATEGORY = "men-shoes"

#: A deliberately sparse category, so the *honest refusal* path stays
#: demonstrable on the same catalog. One product here means an upload into
#: `accessories` has no peer to price against, and the system says so instead
#: of inventing a number. Both behaviours must be reachable.
SPARSE_CATEGORY = "accessories"

RGB = tuple[int, int, int]


@dataclass(frozen=True)
class SeedProduct:
    key: str
    name: str
    brand: str
    price: float
    segment: str
    description: str
    body: RGB
    sole: RGB
    accent: RGB
    variant: int = 0
    category: str = CATEGORY

    @property
    def image(self) -> bytes:
        """Draw the product.

        Silhouette follows the category, so the sparse `accessories` item is
        visually distinct from the footwear -- otherwise image similarity would
        rank it among shoes and muddy the very distinction it exists to show.
        """
        if self.category == SPARSE_CATEGORY:
            return images.backpack(self.body, strap=self.accent, variant=self.variant)
        return images.shoe(
            self.body, self.sole, accent=self.accent, variant=self.variant
        )


_WHITE: RGB = (242, 240, 236)
_GREY: RGB = (96, 100, 108)
_BLACK: RGB = (38, 40, 46)
_BLUE: RGB = (36, 82, 168)
_NAVY: RGB = (22, 46, 96)
_RED: RGB = (186, 52, 44)
_GREEN: RGB = (46, 122, 74)
_ORANGE: RGB = (214, 118, 40)
_YELLOW: RGB = (222, 190, 62)
_PURPLE: RGB = (104, 58, 148)
_TEAL: RGB = (38, 132, 132)
_PINK: RGB = (206, 96, 140)


def _describe(segment: str, colour: str) -> str:
    return (
        f"{colour} {segment} shoe. Synthetic demo product generated by "
        f"scripts/seed_catalog.py for demonstration. Not real catalog data."
    )


def build_catalog() -> tuple[SeedProduct, ...]:
    """Twenty-four shoes: six brands x four segments, on one price scale."""
    return (
        # --- Road running: the deepest segment, so pricing has real evidence.
        SeedProduct(
            "road_01",
            "Demo Velocity Road 7",
            "Northwind",
            8499,
            "road running",
            _describe("road running", "Blue"),
            _BLUE,
            _WHITE,
            _WHITE,
        ),
        SeedProduct(
            "road_02",
            "Demo Velocity Road 7 Wide",
            "Northwind",
            8999,
            "road running",
            _describe("road running", "Blue"),
            _BLUE,
            _WHITE,
            _WHITE,
            variant=4,
        ),
        SeedProduct(
            "road_03",
            "Demo Tempo Glide",
            "Northwind",
            6499,
            "road running",
            _describe("road running", "Teal"),
            _TEAL,
            _WHITE,
            _WHITE,
        ),
        SeedProduct(
            "road_04",
            "Demo Stride Pro Elite",
            "Summit",
            12999,
            "road running",
            _describe("road running", "Black"),
            _BLACK,
            _GREY,
            _ORANGE,
        ),
        SeedProduct(
            "road_05",
            "Demo Stride Daily",
            "Summit",
            5499,
            "road running",
            _describe("road running", "Grey"),
            _GREY,
            _WHITE,
            _BLUE,
        ),
        SeedProduct(
            "road_06",
            "Demo Pace Setter",
            "Meridian",
            9499,
            "road running",
            _describe("road running", "Red"),
            _RED,
            _WHITE,
            _WHITE,
        ),
        SeedProduct(
            "road_07",
            "Demo Pace Setter Lite",
            "Meridian",
            7299,
            "road running",
            _describe("road running", "Orange"),
            _ORANGE,
            _WHITE,
            _GREY,
        ),
        SeedProduct(
            "road_08",
            "Demo Horizon Cushion",
            "Kestrel",
            10499,
            "road running",
            _describe("road running", "Navy"),
            _NAVY,
            _WHITE,
            _YELLOW,
        ),
        # --- Trail: heavier, darker, pricier on average.
        SeedProduct(
            "trail_01",
            "Demo Ridgeline GTX",
            "Summit",
            13499,
            "trail running",
            _describe("trail running", "Green"),
            _GREEN,
            _BLACK,
            _YELLOW,
        ),
        SeedProduct(
            "trail_02",
            "Demo Ridgeline Trail",
            "Summit",
            10999,
            "trail running",
            _describe("trail running", "Black"),
            _BLACK,
            _GREY,
            _GREEN,
        ),
        SeedProduct(
            "trail_03",
            "Demo Boulder Grip",
            "Kestrel",
            11499,
            "trail running",
            _describe("trail running", "Brown"),
            (122, 82, 48),
            _BLACK,
            _ORANGE,
        ),
        SeedProduct(
            "trail_04",
            "Demo Summit Scrambler",
            "Ironwood",
            14999,
            "trail running",
            _describe("trail running", "Navy"),
            _NAVY,
            _BLACK,
            _ORANGE,
        ),
        SeedProduct(
            "trail_05",
            "Demo Fell Runner",
            "Ironwood",
            9999,
            "trail running",
            _describe("trail running", "Purple"),
            _PURPLE,
            _BLACK,
            _WHITE,
        ),
        SeedProduct(
            "trail_06",
            "Demo Canyon Trek",
            "Meridian",
            8999,
            "trail running",
            _describe("trail running", "Grey"),
            _GREY,
            _BLACK,
            _RED,
        ),
        # --- Court: distinct silhouette colours, mid price band.
        SeedProduct(
            "court_01",
            "Demo Baseline Court",
            "Kestrel",
            5999,
            "court",
            _describe("court", "White"),
            _WHITE,
            _GREY,
            _NAVY,
        ),
        SeedProduct(
            "court_02",
            "Demo Baseline Court Pro",
            "Kestrel",
            7999,
            "court",
            _describe("court", "White"),
            _WHITE,
            _GREY,
            _RED,
        ),
        SeedProduct(
            "court_03",
            "Demo Rally Grip",
            "Alder",
            4999,
            "court",
            _describe("court", "Yellow"),
            _YELLOW,
            _WHITE,
            _BLACK,
        ),
        SeedProduct(
            "court_04",
            "Demo Volley Classic",
            "Alder",
            3999,
            "court",
            _describe("court", "Green"),
            _GREEN,
            _WHITE,
            _WHITE,
        ),
        SeedProduct(
            "court_05",
            "Demo Smash Indoor",
            "Meridian",
            6299,
            "court",
            _describe("court", "Blue"),
            _BLUE,
            _WHITE,
            _YELLOW,
        ),
        # --- Lifestyle: the cheapest band, so the catalog has a real spread.
        SeedProduct(
            "life_01",
            "Demo Everyday Canvas",
            "Alder",
            2499,
            "lifestyle",
            _describe("lifestyle", "Black"),
            _BLACK,
            _WHITE,
            _WHITE,
        ),
        SeedProduct(
            "life_02",
            "Demo Everyday Canvas Pink",
            "Alder",
            2699,
            "lifestyle",
            _describe("lifestyle", "Pink"),
            _PINK,
            _WHITE,
            _WHITE,
        ),
        SeedProduct(
            "life_03",
            "Demo Retro Runner 82",
            "Northwind",
            4499,
            "lifestyle",
            _describe("lifestyle", "Red"),
            _RED,
            _WHITE,
            _NAVY,
        ),
        SeedProduct(
            "life_04",
            "Demo City Slip-On",
            "Ironwood",
            3299,
            "lifestyle",
            _describe("lifestyle", "Grey"),
            _GREY,
            _WHITE,
            _WHITE,
        ),
        SeedProduct(
            "life_05",
            "Demo Weekend Low",
            "Kestrel",
            3799,
            "lifestyle",
            _describe("lifestyle", "Purple"),
            _PURPLE,
            _WHITE,
            _WHITE,
        ),
        # --- Deliberately alone in its category.
        #
        # Pricing this product cannot succeed and should not: there is nothing
        # in `accessories` to compare it against. It exists so the honest
        # refusal is demonstrable on the same catalog as a successful estimate,
        # rather than only reachable by breaking something.
        SeedProduct(
            "sparse_01",
            "Demo Trailhead Gym Duffel",
            "Ironwood",
            4299,
            "accessories",
            "Grey gym duffel bag. Synthetic demo product generated by "
            "scripts/seed_catalog.py to demonstrate the no-estimate path -- it is "
            "deliberately the only product in its category. Not real catalog data.",
            _GREY,
            _BLACK,
            _ORANGE,
            category=SPARSE_CATEGORY,
        ),
    )


CATALOG = build_catalog()


def _existing(client: SmokeClient, product: SeedProduct) -> str | None:
    """Return an already-seeded copy's id, or None.

    Idempotent as far as the API permits: matches exactly on name and brand
    among search results, the same approach and the same limits as
    `scripts/smoke/seeding.py` documents.
    """
    try:
        response = client.post_multipart(
            client.api("/products/search"),
            fields={"query": product.name, "top_k": 30},
        )
    except SmokeError:
        # A cold deployment's first search loads a model and can outlast any
        # sane timeout. "Unanswerable" must mean "not present", so we upload.
        return None
    if response.status != 200:
        return None
    try:
        payload = response.json()
    except SmokeError:
        return None
    for result in payload.get("results", []) if isinstance(payload, dict) else []:
        metadata = result.get("metadata") or {}
        if (
            metadata.get("name") == product.name
            and metadata.get("brand") == product.brand
        ):
            found = result.get("product_id")
            if isinstance(found, str):
                return found
    return None


def seed(client: SmokeClient, *, reuse: bool = True) -> tuple[int, int, list[str]]:
    """Upload the catalog. Returns `(created, reused, errors)`."""
    created = reused = 0
    errors: list[str] = []

    for index, product in enumerate(CATALOG, start=1):
        if reuse and _existing(client, product) is not None:
            reused += 1
            print(f"  [{index:2}/{len(CATALOG)}] reused   {product.name}")
            continue

        response = client.post_multipart(
            client.api("/products/upload"),
            fields={
                "name": product.name,
                "brand": product.brand,
                "category": product.category,
                "price": product.price,
                "description": product.description,
            },
            files={"file": (f"{product.key}.png", product.image)},
        )
        if response.status == 202:
            created += 1
            print(f"  [{index:2}/{len(CATALOG)}] uploaded {product.name}")
        else:
            errors.append(
                f"{product.key}: HTTP {response.status} {response.text[:120]}"
            )
            print(
                f"  [{index:2}/{len(CATALOG)}] FAILED   {product.name} (HTTP {response.status})"
            )

    return created, reused, errors


def wait_for_processing(client: SmokeClient, *, timeout: float) -> bool:
    """Block until the queue drains, so the catalog is searchable on return."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        response = client.get(client.api("/system/health"))
        if response.status != 200:
            return False
        depth = response.json().get("queue_depth")
        if depth == 0:
            return True
        print(f"    processing... queue depth {depth}")
        time.sleep(5)
    return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="seed_catalog",
        description="Seed a coherent demo catalog through the real upload API.",
    )
    parser.add_argument(
        "--base-url",
        default=os.environ.get("SMOKE_BASE_URL", "http://localhost:8000"),
        help="API origin (default: %(default)s).",
    )
    parser.add_argument(
        "--timeout", type=float, default=120.0, help="Per-request timeout."
    )
    parser.add_argument(
        "--processing-timeout",
        type=float,
        default=1800.0,
        help="Seconds to wait for the queue to drain (default: %(default)s).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Upload everything again instead of reusing what is already indexed.",
    )
    parser.add_argument(
        "--no-wait",
        action="store_true",
        help="Return as soon as uploads are queued, without waiting for processing.",
    )
    parser.add_argument(
        "--list", action="store_true", help="Print the catalog and exit."
    )
    args = parser.parse_args(argv)

    if args.list:
        by_category: dict[str, int] = {}
        for item in CATALOG:
            by_category[item.category] = by_category.get(item.category, 0) + 1
        summary = ", ".join(
            f"{count} {name}" for name, count in sorted(by_category.items())
        )
        print(f"Demo catalog: {len(CATALOG)} products ({summary}).")
        print(CURRENCY_NOTE)
        for product in CATALOG:
            print(
                f"  {product.key:10} {product.name:34} {product.brand:10} "
                f"{product.price:>7} {product.category:12} {product.segment}"
            )
        return 0

    client = SmokeClient(base_url=args.base_url, timeout=args.timeout)
    print(f"Seeding {len(CATALOG)} products into {client.base_url}")
    print(CURRENCY_NOTE)
    print()

    created, reused, errors = seed(client, reuse=not args.force)
    print()
    print(f"  uploaded {created}, reused {reused}, failed {len(errors)}")
    for error in errors:
        print(f"    {error}")

    if created and not args.no_wait:
        print()
        print("  waiting for the pipeline to finish...")
        if not wait_for_processing(client, timeout=args.processing_timeout):
            print(
                "  timed out waiting for the queue to drain; products may still be processing"
            )
            return 1

    print()
    print("Catalog ready.")
    return 1 if errors else 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\ninterrupted", file=sys.stderr)
        sys.exit(2)
